### ISSUE TITLE
building the project

### ISSUE THREAD

**Issue by sadovnikov** [aroundthecode/pathfinder#1]
hi,

I'm very curious about your project and therefore tried to build it. However regular `mvn clean install` in the very root of the project has failed on tests in `pathfinder-server`. Before I start debugging the problem, is it something already known to you? any you maybe have a known solution?

I didn't find any specific requirements for building. `.travis.yml` is nearly empty and seems Travis CI succeeds building it... although it requires `oraclejdk8` and `pom.xml` states `<java.version>1.7</java.version>`

```
Tests in error: 
  test10Client(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
  test20Write(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
  test30Dependencies(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
  test40Parent(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
  test50Read(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
  test60Crawler(org.aroundthecode.pathfinder.server.controller.PathFinderControllerTest): Failed to load ApplicationContext
```

My both default java and `JAVA_HOME` are `jdk1.8.0_40.jdk`

```
vikmac:pathfinder vik$ which java
/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java
vikmac:pathfinder vik$ echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home
```

The cause seems to be

```
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'graphDatabaseService': Requested bean is currently in creation: Is there an unresolvable circular reference?
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:347) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
```

Any tips?

With regards,
Viktor

**Comment by sadovnikov** [comment]
@mikesac, of course, I could build the project without test. However, unfortunately, the same errors occur on `mvn clean package spring-boot:run` on attempt to start the server https://github.com/aroundthecode/pathfinder/tree/develop/pathfinder-server ;(

**Comment by aroundthecode** [comment]
Hi Viktor, thanks for your interest in the project.
I've re-downlod the full package from github into a separate folder and both server and test run correctly, which Os are you running on? 

Maybe you can try also commit https://github.com/aroundthecode/pathfinder/commit/fbd71254b854e149896843b6f44ce4cdc6172952 which is a jar version of the server, while latest commit is a war one and maybe it's causing some issue.

I'm experiencing that king of "circural reference" error while trting to upgrade to latest spring boot/data version, but it's quite strange you are getting them on current version. Could you try with JDK 1.7 as well? (travis parameter are used by travisCi only)

Let me know if this helps.

**Comment by sadovnikov** [comment]
Will do !!!

**Comment by sadovnikov** [comment]
I took a closer look at the tests failures. Seems the error I have reported is a secondary one. The initial problem is port `8080` being occupied on my laptop and changing value of `<server.port>8080</server.port>` in `pom.xml` is not enough. If I change this value, logs still report attempts and failures to open 8080. 

After I stopped the application, which was occupying 8080, nearly all tests succeed, except `PathFinderControllerTest.test60Crawler(PathFinderControllerTest.java:118)`: `obj.get("return")` comes back with -1 instead of 0. 

There is a warning in logs of the test

```
01:33:06.887 [main] WARN  org.aroundthecode.pathfinder.server.crawler.CrawlerWrapper - No M2_HOME set, using [/opt/apache-maven]
```

Can this be a reason?

**Comment by sadovnikov** [comment]
I'm on MAC OSX

**Comment by aroundthecode** [comment]
Hi Viktor
about managing pathfinder-server port you can find details at https://github.com/aroundthecode/pathfinder/tree/develop/pathfinder-server , there are both application server port and neo4j server port which may cause clash on already-existing application.

About the last error you get, Crawler (sorry still no documentation on it) needs a maven installation local to pathfinder-server installation to work, therefore it looks for environment varialbe M2_HOME to locate it, if not found it will fallback to /opt/apache-maven as stated in the logs.

You could skip such test and have a working server but without maven there is actually no way to populate pathfinder neo4j DB so it would be an empty installation.

you can refer to documentation pages on github and my blog posts as well for a deeper lok at crawler / maven functionalities https://aroundthecode.org/category/opensourceproject/pathfinder/

I'm on MacosX too so i'm expecting your setup to work properly.

**Comment by sadovnikov** [comment]
merge of #2 and #3 resolved the problem
