### ISSUE TITLE
Could not find artifact org.neo4j:neo4j-cypher-dsl:jar:2.0.1 in maven-release

### ISSUE THREAD

**Issue by ranjith-murugasamy** [aroundthecode/pathfinder#12]
Downloading: http://repo.maven.apache.org/maven2/org/neo4j/neo4j-cypher-dsl/2.0.1/neo4j-cypher-dsl-2.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.490 s
[INFO] Finished at: 2018-10-15T11:02:44+05:30
[INFO] Final Memory: 18M/248M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pathfinder-server: Could not resolve dependencies for project org.aroundthecode.pathfinder:pathfinder-server:war:0.1.0-SNAPSHOT: Could not find artifact org.neo4j:neo4j-cypher-dsl:jar:2.0.1 in maven-release (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by wtroughton** [comment]
Go with pathfinder/pom.xml and modify the Neo4j repository url to http://m2.neo4j.org/content/repositories/releases/

```
<repository>
	<id>neo4j</id>
	<name>Neo4j</name>
	<url>http://m2.neo4j.org/content/repositories/releases/</url>
</repository>
```

**Comment by aroundthecode** [comment]
Pom updated
Thanks @wtrought for che King and sorry for the late fix.
Also update sonar referente for new online platform
